src/Entity/Commande.php
<?php

namespace App\Entity;

use App\Repository\CommandeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CommandeRepository::class)]
class Commande
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $date_commande = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 7, scale: 2)]
    private ?string $total = null;

    #[ORM\Column]
    private ?int $etat = null;

    #[ORM\OneToMany(mappedBy: 'commande', targetEntity: Detail::class, orphanRemoval: true)]
    private Collection $detail;

    #[ORM\ManyToOne(inversedBy: 'commande')]
    private ?User $user = null;

    public function __construct()
    {
        $this->detail = new ArrayCollection();
    }

    public function getDateCommande(): ?\DateTimeImmutable
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeImmutable $date_commande): self
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(string $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function getEtat(): ?int
    {
        return $this->etat;
    }

    public function setEtat(int $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    /**
     * @return Collection<int, Detail>
     */
    public function getDetails(): Collection
    {
        return $this->detail;
    }

    public function addDetail(Detail $detail): self
    {
        if (!$this->detail->contains($detail)) {
            $this->detail->add($detail);
            $detail->setCommande($this);
        }

        return $this;
    }

    public function removeDetail(Detail $detail): self
    {
        if ($this->detail->removeElement($detail)) {
            // set the owning side to null (unless already changed)
            if ($detail->getCommande() === $this) {
                $detail->setCommande(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of id
     */ 
    public function getId()
    {
        return $this->id;
    }
}

src/Controller/StripeController.php
<?php
 
namespace App\Controller;

use Stripe;
use App\Entity\Commande;
use App\Service\CartService;
use App\Repository\PlatRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
 
class StripeController extends AbstractController
{
    #[Route('/stripe/{commande}', name: 'app_stripe')]
    public function index(Request $request, Commande $commande, PlatRepository $repo): Response
    {
        $session = $request->getSession();
        $panier = $session->get('cart', []);

        foreach($panier as $id => $quantite)
        {
            $plat = $repo->find($id);
            $plats[] = $plat;
            $quantites[$id] = $quantite;
        }       

        return $this->render('stripe/index.html.twig', [
            'stripe_key' => 'pk_test_51N0js9CjO1FIa7oUl6LUVyqSTEvaDZglojbVHB6pUyYD4uQGTqsU8ZGOI5XcRpNtHhNwWxd6VVJZgFi3dWoOz15k00jhs9ESsv',
            'commande' => $commande,
            'plats' => $plats,
            'quantites' => $quantites
        ]);
    }
 
 
    #[Route('/stripe/create-charge/{commande}', name: 'app_stripe_charge', methods: ['POST'])]
    public function createCharge(Request $request, Commande $commande, CartService $cartService)
    {
        Stripe\Stripe::setApiKey('sk_test_51N0js9CjO1FIa7oUhKvQznKvDRO7PBtCu8QVAiXXVR6rXjnd14yFskpIhk0v1qQmmMqe7hXQHxViHLT8SMQNGRtx00hYsctv1E');
        Stripe\Charge::create ([
                "amount" => $commande->getTotal() * 100,
                "currency" => "eur",
                "source" => $request->request->get('stripeToken')
        ]);
        $this->addFlash(
            'success',
            'Payment Successful!'
        );

        $cartService->removeCartAll();
        return $this->redirectToRoute('home', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * Set the value of repo
     *
     * @return  self
     */ 
    public function setRepo($repo)
    {
        $this->repo = $repo;

        return $this;
    }
}

templates/stripe/index.html.twig
{% extends "base.html.twig" %}

{% block title %} Payment{% endblock %}

{% block body %}
<div class="container">
    <h1 class="mt-4">commande</h1>
    <div class="row">
        <div class="col-4 m-4 bg-dark text-white">
            <h2 class="justify-content-center text-white">liste de la commande</h2>
            <div class="d-flex justify-content-between">
                <p>
                    Numero: {{ commande.id }}
                </p>
                <p>
                    Date: {{ commande.dateCommande|date('d/m/Y') }}
                </p>
            </div>
            {% set i = 0 %}
            {% set total = 0 %}
            {% for plat in plats %}
            {% set i = i + 1 %}
            {% set ptotal = 0 %}
            {% set ptotal = plat.prix * quantites[plat.id] %}
            {% set total = total + ptotal %}
            <div class="row">
                <div class="col-1">
                    {{ i }}
                </div>
                <div class="col-4">
                    {{ plat.libelle }}
                </div>
                <div class="col-2">
                    {{ plat.prix }}€
                </div>
                <div class="col-2">
                    {{ quantites[plat.id] }}
                </div>
                <div class="col-2">
                    {{ptotal}}.00€
                </div>
            </div>
            {% endfor %}
            <div class="d-flex justify-content-end me-4">{{ total }},00€</div>
            <br>
            <div class="row">
                <div class="col-2">
                    Nom:
                </div>
                <div class="col-4">
                    {{ commande.user.nom }} {{ commande.user.prenom }}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    Adresse:
                </div>
                <div class="col-9">
                    {{ commande.user.adresse }} {{ commande.user.cp }} {{ commande.user.ville }}
                </div>
            </div>
            <div class="row">
                <div class="col-2">
                    Email:
                </div>
                <div class="col-2">
                    {{ commande.user.email }}
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    Num Tel:
                </div>
                <div class="col-2">
                    {{ commande.user.telephone }}
                </div>
            </div>
        </div>
        <div class="justify-content-center col-4">
            <div class="card m-4">
                <div class="card-body">
                    {% for message in app.flashes('success') %}
                    <div style="color: green;
                                border: 2px green solid;
                                text-align: center;
                                padding: 5px;margin-bottom: 10px;">
                        {{ message }}
                    </div>
                    {% endfor %}
                    {% set payer = commande.total %}
                    <form id='checkout-form' method='post'
                        action="{{ path('app_stripe_charge',{commande: commande.id }) }}">
                        <input type='hidden' name='stripeToken' id='stripe-token-id'>
                        <label for="card-element" class="mb-5">Payment la commande</label>
                        <br>
                        <div id="card-element" class="form-control"></div>
                        <button id='pay-btn' class="btn btn-pimary mt-3" type="button"
                            style="margin-top: 20px; width: 100%;padding: 7px;" onclick="createToken()">payer {{ payer
                            }}€
                        </button>
                        <form>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="https://js.stripe.com/v3/"></script>
<script>
    var stripe = Stripe("{{stripe_key}}");
    var elements = stripe.elements();
    var cardElement = elements.create('card');
    cardElement.mount('#card-element');

    function createToken() {
        document.getElementById("pay-btn").disabled = true;
        stripe.createToken(cardElement).then(function (result) {


            if (typeof result.error != 'undefined') {
                document.getElementById("pay-btn").disabled = false;
                alert(result.error.message);
            }

            // creating token success
            if (typeof result.token != 'undefined') {
                document.getElementById("stripe-token-id").value = result.token.id;
                document.getElementById('checkout-form').submit();
            }
        });
    }
</script>
{% endblock %}